import React from 'react';

const page= ()=>{
    return(
        <div className='flex flex-col p-[1rem] items-center justify-center gap-[2rem]'>
            <div className='flex flex-col items-center justify-center gap-[1rem] p-[1rem]'>
                <h1 className='text-2xl md:text-4xl font-bold'>TERMS OF SERVICE</h1>
                <h4 className='text-md'>Last Revised: 03.25.2024</h4>
            </div>
            <div className='text-xs md:text-sm  flex flex-col gap-[1rem] sc2:text-lg sc2:gap-[2rem] pl-[2rem] md:pl-[0.5rem] sc2:pl-0'>
                <div>
                These Terms of Service (the <span className='font-bold'>“Terms”</span> ) constitute a legally binding agreement made between you, whether personally or on behalf of an entity (<span className='font-bold'>“you”</span>), and <span className='font-bold'>Remex Foundation</span> (<span className='font-bold'>“Remex,” “we,”</span> or <span className='font-bold'>“us”</span> ), concerning your access to and use of the Remexfi.com website (the <span className='font-bold'>“Website”</span> ), Remex web applications, and our related websites, hosted applications, mobile or other downloadable applications (collectively, the “Services”). By accessing or using the Services, you agree that you have read, understand, and accept all of the terms and conditions contained in the Terms. If you do not agree to all of the terms and conditions of the Terms, you may not access or use the Services
                </div>
                <div>
               <span className='underline underline-offset-4'>Amendment of the Terms. </span> We may amend or modify the Terms at any time by posting the revised agreement on the Website and/or providing a copy to you (“Revised Terms”). Such Revised Terms shall be effective as of the time the Revised Terms are posted. Your continued use of the Services after the posting of Revised Terms constitutes your acceptance of such Revised Terms. If you do not agree with any such modifications, your sole and exclusive remedy is to terminate your use of the Services. 
                </div>
                <div>
                <span className='underline underline-offset-4'>Technical Services Only. </span> THE SERVICES INCLUDE, AMONG OTHER THINGS, A WEB-BASED INTERFACE THAT ALLOWS USERS TO INTERACT WITH A NON-CUSTODIAL DECENTRALIZED SOFTWARE PROTOCOL THAT OPERATES ON A PERMISSIONLESS PUBLIC BLOCKCHAIN. Remex IS NOT A BROKER, DEALER, EXCHANGE, INVESTMENT ADVISER, CUSTODIAN OR FINANCIAL SERVICE PROVIDER OF ANY KIND. THE SERVICES INCLUDE TECHNICAL SERVICES THAT ENABLE USERS TO ACCESS AND INTERACT WITH ONCHAIN SMART CONTRACTS THAT FUNCTION DETERMINISTICALLY AND ARE NOT OPERATED OR CONTROLLED BY Remex. WE DO NOT HAVE A FIDUCIARY RELATIONSHIP OR OBLIGATION TO YOU IN CONNECTION WITH THE SERVICES. 
                </div>
                <div>
                <span className='underline underline-offset-4'>Binding Arbitration; Class Action and Jury Trial Waiver. </span> PLEASE BE AWARE THAT SECTION 9 (DISPUTE RESOLUTION; AGREEMENT TO ARBITRATE) GOVERNS THE RESOLUTION OF DISPUTES BETWEEN YOU AND Remex. SECTION 9 INCLUDES AN AGREEMENT TO ARBITRATE WHICH REQUIRES, WITH LIMITED EXCEPTIONS, THAT ALL DISPUTES BETWEEN YOU AND US SHALL BE RESOLVED BY BINDING AND FINAL ARBITRATION. SECTION 9 ALSO CONTAINS A CLASS ACTION AND JURY TRIAL WAIVER. PLEASE READ SECTION 9 CAREFULLY. 
                </div>
                <div>
                <span className='underline underline-offset-4'>Privacy Policy. </span> Your personal information and privacy are important to us. The collection, use, and sharing of your personal information through the Services and while you use the Services are subject to our Privacy Policy [https://www.Remexfi.com/docs/privacy], which is hereby incorporated into the Terms. 
                </div>
                <div className='flex flex-col gap-[1rem]'>
                    <ul className='flex flex-col gap-[2rem]'>
                    <li>
                        <span className='font-bold'>1. Eligibility. </span>To be eligible to access or use the Services, you must satisfy each of the following eligibility requirements:
                        <div className='flex flex-col gap-[2rem] pl-[2%]'>
                               <div>1.1. You are at least eighteen (18) years of age, or are the legal age for entering legally binding agreements under applicable law; </div> 

                               <div> 1.2. You are not, nor are you an entity that is, or an entity owned or controlled by any person or entity that is, or conducting any activities itself or on behalf of any person or entity that is: the subject of any sanctions administered or enforced by the U.S. Department of the Treasury’s Office of Foreign Assets Control, the U.S. Department of State or any other governmental authority with jurisdiction over the party; identified on the Denied Persons, Entity or Unverified</div>

                               <div> Lists of the U.S. Department of Commerce’s Bureau of Industry and Security; or located, organized or resident in a country or territory that is, or whose government is, the subject of economic sanctions, including, without limitation, Russia, Crimea, Cuba, Iran, North Korea or Syria (each, a “Restricted Person”); </div>

                               <div> 1.3. You are not, nor are you an entity that is, or an entity owned or controlled by any person or entity that is, or conducting any activities itself or on behalf of any person or entity that is: (i) a natural person resident in the United States; (ii) a partnership or corporation organized or incorporated under the laws of the United States; or (iii) otherwise a “U.S. person” as defined in Rule 902(k)(2) of Regulation S under the Securities Act of 1933 (each, a “U.S. Person”); and </div>

                               <div> 1.4. You are not accessing or using the Services on behalf of a Restricted Person or U.S. Person. </div>
                        </div>        
                    </li>
                    <li>
                        <span className='font-bold'>2. The Protocol. </span>
                        <div className='flex flex-col gap-[2rem] pl-[2%]'>
                            <div>  2.1. The Protocol and the Services .. The Remex protocol (the “Protocol”) is an open-source blockchain software protocol that is available alongside the Services. The Services include a user interface that allows users to access and interact with the Protocol, but the user interface is not the exclusive or sole means to do so. Please review the Protocol software code and related documentation before using the Services to access or interact with the Protocol to learn more about the rules and requirements of the Protocol. For the avoidance of doubt, the Protocol is not a part or component of the Services. Remex does not control or operate the Protocol</div>
                            <div> 2.2. Prior Versions of the Protocol .. New versions and upgrades to the Protocol may be released from time to time. The Services may not be compatible with prior, abandoned, or outdated versions of the Protocol. Remex undertakes no responsibility or obligation to update or maintain support for legacy versions of the Protocol</div>
                            <div>  2.3. Testnet .. Subject to the terms and conditions of this Agreement, you may use the Services to access and interact with a “test network” version of the Protocol for purposes of experimenting with the Protocol within a test environment (the “Testnet”). Your transactions on the Testnet shall solely be for experimental and educational purposes only and shall not be reflected on the Base layer-two “main network” and/or Ethereum blockchain “main network.” Crypto assets transacted with or acquired on the Testnet have no market value and cannot be transferred to any “main network"</div>
                            <div>  2.4. Protocol Fees .. You acknowledge and agree that the Protocol may from time to time assess service fees (“Protocol Fees”) directly from you in accordance with Protocol rules. The current Protocol Fees are set forth at [https://docs.Remexfi.com/rewards/revenue-distribution]</div>
                            <div>  2.5. Informational Resources . We may make certain informational resources relating to the Protocol, including, without limitation, the docs at docs.Remexfi.com, blog posts, data, articles, tutorials, social media posts and other content (“Informational Resources”), available to you as part of the Services. You acknowledge and agree that all such Informational Resources are intended for informational and educational purposes only and are not the exclusive or sole source of information regarding the Protocol. Remex shall not be responsible or liable for any damage or loss caused or alleged to be caused by or in connection with the use or reliance on any Informational Resources</div>
                            <div>  2.6. Experience Points (“XP”) . You may from time to time earn rewards experience points (“XP”) in connection with your use of the Protocol. XP are solely for fun and friendly competition within the Protocol. XP are non-transferable, are not redeemable for cash or crypto assets and do not have any cash or crypto asset value. The sale or barter or XP, or the attempt of the foregoing, is prohibited. All XP are natively generated and rewarded deterministically pursuant to preprogrammed parameters. The mechanics of the XP reward system may differ during different defined time periods or “seasons".</div>
                         </div>
                    </li>
                    <li>
                    <span className='font-bold'>3. Acessing the services. </span>
                    <div className='flex flex-col gap-[2rem] pl-[2%]'>
                               <div> 3.1. Connecting a Wallet. To access and use certain aspects of the Services, you will be required to connect a compatible Ethereum blockchain digital wallet (“Wallet”). By connecting a Wallet to the Services, you agree to abide by the terms and conditions of the applicable software provider or developer that makes the applicable Wallet software available to you. You are solely responsible for reviewing the terms of use, technology, and security protocols associated with your Wallet software. Remex does not offer Wallet software or take custody, possession or control of your crypto assets at any time. You are solely responsible for maintaining the security of your Wallet, including your credentials, private key, and/or seed phrase. Remex shall not be liable for any acts or omissions by you in connection with your Wallet or any security incident related to your Wallet. </div>

                               <div> 3.2. Bridging to Base. The Protocol is currently available solely on Base, a layer-two optimistic rollup network that operates on the Ethereum layer-one blockchain. Before you are able to use the Protocol, you will need to transfer or “bridge” crypto assets within your Wallet on Ethereum to Base using third-party bridge software. You acknowledge and understand that Remex does not offer bridge software to users. Crypto assets that have not been bridged to Base cannot be used in transactions on the Protocol. Once you have bridged crypto assets to Base, such crypto assets cannot be used on Ethereum until such crypto assets have been “withdrawn” from Base. The crypto assets that you bridge to Base will appear in your Wallet on Base, but will not appear in your Wallet on Ethereum. The crypto assets that you withdraw will no longer appear in your Wallet on Base but will appear in your Wallet on Ethereum. If you attempt to bridge any crypto assets that are not supported by a bridge designed for Base, you may destroy or irretrievably lose access to such crypto assets. You own, control, and are responsible for all crypto assets held in and bridged via your Wallet and Remex shall not be liable or responsible for any crypto assets that are destroyed or irretrievably lost by you through the bridging and withdrawing process. Your use of Base is subject to the Base Terms of Service available at https://docs.base.org/terms-of-service. Please carefully review these terms and conditions before bridging any crypto assets to Base.</div>

                               <div> The crypto assets that you bridge to Base will appear in your Wallet on Base, but will not appear in your Wallet on Ethereum. The crypto assets that you withdraw will no longer appear in your Wallet on Base but will appear in your Wallet on Ethereum. If you attempt to bridge any crypto assets that are not supported by a bridge designed for Base, you may destroy or irretrievably lose access to such crypto assets. You own, control, and are responsible for all crypto assets held in and bridged via your Wallet and Remex shall not be liable or responsible for any crypto assets that are destroyed or irretrievably lost by you through the bridging and withdrawing process. Your use of Base is subject to the Base Terms of Service available at https://docs.base.org/terms-of-service. Please carefully review these terms and conditions before bridging any crypto assets to Base. </div>
                    </div>
                    </li>
                    <li>
                    <span className='font-bold'>4. Prohibited Activities.  </span>
                    <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>   4.1. You shall not engage in any activities that negatively affect the technical performance of the Services, bypass or circumvent security features of the Services, or otherwise disrupt or interfere with the functioning of the Services. You shall not violate or attempt to violate the security of the Services or otherwise misuse the foregoing, including by, (i) accessing data not intended for you or logging onto a server or an account which you are not authorized to access; (ii) disabling, removing, defeating or avoiding any security device or system; (iii) attempting to probe, scan or test the vulnerability of the Services or to breach security or authentication measures without proper authorization; (iv) attempting to interfere with Services functionality, including, but not limited to, via means of submitting any malware or computer programming routines that may damage, disrupt or interfere with, intercept or expropriate any system or data, overloading, “flooding,” “spamming,” “mailbombing” or “crashing” the Services; (v) forging any transmission control protocol/internet protocol packet header or any part of the header information in any email or posting; (vi) using the Services in a manner that exceeds reasonable request volume or constitutes excessive or abusive usage; or (vii) providing false, misleading or inaccurate information to the Services. </div>

                    <div>           4.2. You shall not, directly or indirectly: (i) disassemble, decompile, reverse engineer or use any other means to attempt to discover any source code of the Services, or the underlying ideas, file formats, algorithms or trade secrets therein; (ii) encumber, sublicense, transfer, rent, lease, time-share or use the Services in any service bureau arrangement or otherwise for the benefit of any third party; (iii) copy, distribute, manufacture, adapt, create derivative works of, translate, localize, port or otherwise modify any software code or documentation for the Services; (iv) knowingly introduce into the Services any malicious code, computer virus, spyware, scareware, Trojan horses, worms, malware or any other similar harmful, malicious or hidden programs or data; (v) use the Services to infringe upon, violate or misappropriate any third party's intellectual property rights, violating any law or regulation or being defamatory, trade libelous, threatening or harassing; or (vi) authorize or permit any third party to engage in any of the foregoing proscribed acts. For the avoidance of doubt, the restrictions set forth in this Section are in addition to, and in no way limit, any other restrictions or obligations applicable to you set forth in the Terms. </div>

                    <div>           4.3. You shall not use the Services to engage in illegal activity of any kind, including, without limitation, any activity that would violate, or assist in violation of, any law, statute, ordinance, regulation or sanctions programs administered under any applicable law, including but not limited to the U.S. Department of Treasury's Office of Foreign Assets Control or which would involve proceeds of any unlawful activity. </div>
                    </div>
                    </li>
                    <li>
                    <span className='font-bold'>5. Intellectual Property.</span> 
                    <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>      5.1. License. The Services you have accessed and all of its contents as a whole and in part are protected by copyrights, trademarks, service marks, trade names, international treaties, and/or other proprietary rights and applicable laws, and are owned or controlled by Remex, its affiliates and licensors. You agree to protect the proprietary rights of us and all others having rights in the Services. Subject to the Terms, we grant you a limited, revocable, non-exclusive, non-sublicensable, non-transferable license to use the Services for your own personal or legitimate business purposes. You acquire absolutely no rights or licenses in or to the Services or materials contained within the Services other than the limited right for you to access and use the Services in accordance with the Terms. Except for the limited license granted in these Terms, Remex and its licensors retain all right, title, interest and all proprietary rights in and to the Services, including without limitation copyrights, patents, trademarks, service marks and trade names. Remex may change, suspend, or discontinue any aspect of the Services at any time, without any liability or obligation to you. Remex, its licensors and service providers reserve all rights not granted in these Terms. </div>

                    <div>         5.2. Third-Party Licenses. Notwithstanding anything to the contrary in the Terms, the Services may contain software components released under separate open-source or business-source license terms, in which case those license terms will govern such software components. </div>

                    <div>          5.3. Feedback. With respect to any feedback you provide to Remex (whether orally or in writing) concerning the Services, including any features or functionalities thereof, and including identifying potential errors and improvements (“Feedback”), you hereby grant to Remex an exclusive, worldwide, perpetual, fully paid-up, royalty free, fully-sublicensable (through multiple tiers of sublicensees) and freely assignable and transferable license to use any Feedback for any purpose without payment or restriction. It is further understood that Remex’s use of Feedback, if any, may be made by Remex in its sole discretion, and that Remex shall in no way be obliged to make any payment to you for or make use of any kind of the Feedback or part thereof. </div>

                    <div>          5.4. Use of Trademarks and Other Marks or Rights. You may not use any of our trademarks, trade names, service marks, copyrights, or logos, or our partners’, affiliated entities’, licensors’, or their licensors’ trademarks, trade names, service marks, copyrights, or logos, including but not limited to Remex, in any manner which creates the impression that such items (i) belong to or are associated with you or indicate the sponsorship or approval of us, our licensors, any partners, affiliates, or their licensors; or (ii) except as otherwise provided herein, are used with our licensors’, partners’, affiliates’, or their licensors’ consent, and you acknowledge that you have no ownership rights in or to any such items. </div>
                    </div>
                    </li>
                    <li>
                    <span className='font-bold'>6. Term; Termination.</span>
                    <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>    6.1. The Terms are effective beginning when you accept the Terms or first access or use the Services and ending when terminated as set forth in Section 6.2. </div>

                    <div>   6.2. Your right to use and access the Services will automatically terminate in the event you fail to comply with any of the terms and conditions of the Terms. Termination will be effective without notice. </div>

                    <div>    6.3. Upon termination of the Terms, your license rights will immediately terminate and you must immediately cease all use of the Services. Sections 4-11 of the Terms shall survive any such termination. </div>
                    </div>
                    </li>
                    <li>
                    <span className='font-bold'>7.Risks. </span>
                    <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>           7.1. You acknowledge and understand that the Services may not be available or appropriate for use in all jurisdictions and you may be subject to legal and regulatory compliance obligations in connection with your use of the Services in certain jurisdictions. By accessing or using the Services, you agree that you are solely and entirely responsible for compliance with all laws and regulations that may apply to you. You further agree that we have no obligation to inform you of any potential liabilities or violations of law or regulation that may arise in connection with your access and use of the Services and that we are not liable in any respect for any failure by you to comply with any applicable laws or regulations. </div>

                    <div>            7.2. You acknowledge that the Services incorporate experimental and novel technology and that the use of such technology involves a high degree of risk. For example, there are numerous reasons the Services and/or Protocol could fail in an unexpected way, resulting in the total and absolute loss of your crypto assets. You hereby agree that you assume all risks in connection with your use of the Services and expressly waive and release Remex from any and all liability, claims, causes of action or damages arising out of or in any way relating to you obtaining or using Services. </div>

                    <div>           7.3. You understand accept the risk of operational challenges related to the Services. For example, the Services may experience cyber-attacks, unexpected surges in transaction volume or activity or other operational or technical difficulties or vulnerabilities that may cause interruptions related to your use of the Services. You agree to accept the risk of a failure of the Services and/or Protocol resulting from unanticipated or heightened technical difficulties or vulnerabilities, including those resulting from cyber-attacks. You agree not to hold Remex liable for any related losses. </div>

                    <div>           7.4. You agree that Remex is not responsible for any crypto assets that you receive, transfer, hold, lose or otherwise use or misuse in connection with the Services. Additionally, you agree that Remex is not responsible for any tax obligations that you incur in connection with your use of the Services. </div>

                    <div>           7.5. You understand that all transactions conducted through the Protocol are automatically processed onchain through smart contracts. By engaging in transactions using the Services, you acknowledge and consent to the automatic processing of all transactions in connection with the Services. You acknowledge and agree that the applicable smart contract will programmatically facilitate the transfer of crypto assets in connection with your transactions. You further acknowledge and agree that Remex does not take possession, custody or control over your crypto assets at any time. </div>
                </div>
                </li>
                <li>
                <span className='font-bold'>8. Disclaimer of Warranties; Limitation of Liability; Indemnification.</span>
                    <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>           8.1. EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SERVICES ARE ISSUED ON AN “AS-IS” AND “AS AVAILABLE” BASIS AND Remex DOES NOT MAKE ANY WARRANTIES WITH RESPECT TO SUCH “AS-IS” AND “AS AVAILABLE” BASIS OR OTHERWISE IN CONNECTION WITH THE TERMS (EXCEPT AS EXPRESSLY PROVIDED HEREIN) AND Remex HEREBY DISCLAIMS ANY AND ALL EXPRESS, IMPLIED OR STATUTORY WARRANTIES AND CONDITIONS, INCLUDING ANY WARRANTIES OR CONDITIONS OF NON-INFRINGEMENT, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AVAILABILITY, ERROR-FREE OR UNINTERRUPTED OPERATION, AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. TO THE EXTENT THAT Remex MAY NOT, AS A MATTER OF APPLICABLE LAW, DISCLAIM ANY IMPLIED WARRANTY OR CONDITION, THE SCOPE AND DURATION OF SUCH WARRANTY OR CONDITION SHALL BE APPLIED TO THE MINIMUM EXTENT PERMITTED UNDER SUCH APPLICABLE LAW. </div>

                    <div>            8.2. IN NO EVENT SHALL Remex BE LIABLE TO YOU FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL OR SPECIAL DAMAGES OF ANY TYPE OR NATURE HOWEVER ARISING, INCLUDING, WITHOUT LIMITATION, EXEMPLARY OR PUNITIVE DAMAGES, LOST PROFITS OR REVENUES OR DIMINUTION IN VALUE, ARISING OUT OF OR RELATING TO THE SERVICES OR THE PROTOCOL, WHETHER OR NOT THE POSSIBILITY OF SUCH DAMAGES HAS BEEN DISCLOSED TO OR COULD HAVE BEEN REASONABLY FORESEEN BY YOU, REGARDLESS OF THE LEGAL OR EQUITABLE THEORY (CONTRACT, TORT OR OTHERWISE) UPON WHICH THE CLAIM IS BASED. IN ADDITION, UNDER NO CIRCUMSTANCES SHALL Remex’S AGGREGATE LIABILITY UNDER THE TERMS EXCEED ONE-HUNDRED U.S. DOLLARS ($100.00). </div>

                    <div>            8.3. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH THE SERVICES, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICES. </div>

                    <div>           8.4. You agree, at your own expense, to indemnify, defend, and hold harmless us and our partners and affiliates and their respective owners, members, agents, directors, officers, employees, representatives, affiliates, successors, and assigns against any claim, suit, action, or other proceeding from and against any and all claims, damages, liabilities, costs, and expenses, including reasonable attorneys’ and experts’ fees, arising out of or in connection with the Services, or any links on the Services, including but not limited to: (i) any breach or violation of the Terms by you; (ii) material, information, or content submitted or provided by you; (iii) your use of the Services; or (iv) any deletions, additions, insertions, or alterations to, or any unauthorized use of, the Services by you. You agree to pay any and all costs, damages, and expenses, including but not limited to reasonable attorneys’ fees and costs awarded against or otherwise incurred by or in connection with or arising from any such claim, suit, action, or proceeding attributable to any such claim. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with us in asserting any available defense. </div>
                </div>
                </li>
                <li>
                <span className='font-bold'>9. Dispute Resolution; Agreement to Arbitrate.</span>
                <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>        9.1. All disputes, claims and controversies, whether based on past, present or future events, arising out of or relating to statutory or common law claims, the breach, termination, enforcement, interpretation or validity of any provision of the Terms, and the determination of the scope or applicability of your agreement to arbitrate any dispute, claim or controversy originating from the Terms, will be determined by binding arbitration in [the State of Delaware],2Cayman Islands, before a single arbitrator. The arbitration will be administered by the American Arbitration Association (“AAAInternational Centre for Dispute Resolution (“ICDR”), in accordance with the ConsumerInternational Arbitration Rules (of the “AAA Rules”) then in effect, except as modified by this Section 9. The AAA Rules are currently available at https://www.adr.org/sites/default/files/Consumer%20Rules.pdf.ICDR. </div>

                    <div>          9.2. The arbitrator will apply the substantive law of the Cayman Islands, excluding its conflict or choice of law rules. </div>

                    <div>           9.3. Nothing in the Terms will preclude the parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction. </div>

                    <div>           9.4. A party must notify the other party of its intent to commence arbitration prior to commencing arbitration. You may provide such notice to Remex by email at info@Remexfi.com. The notice must specify the date on which the arbitration demand is intended to be filed, which must be at least thirty (30) days after the date of the notice. During this time period, the parties will meet for the purpose of resolving the dispute prior to commencing arbitration. </div>

                    <div>            9.5. Subject to Section 9.4, each party may commence arbitration by providing to the ICDR and the other party to the dispute a written demand for arbitration, stating the subject of the dispute and the relief requested. </div>

                    <div>            9.6. Subject to the disclaimers and limitations of liability stated in the Terms, the appointed arbitrators may award monetary damages and any other remedies allowed by the laws of [the Cayman Islands. In making a determination, the arbitrator will not have the authority to modify any term of the Terms. The arbitrator will deliver a reasoned, written decision with respect to the dispute to each party, who will promptly act in accordance with the arbitrator’s decision. Any award (including interim or final remedies) may be confirmed in or enforced by a court located in Cayman Islands. The decision of the arbitrator will be final and binding on the parties, and will not be subject to appeal or review. </div>
                                
                        <div>            9.7. Subject to applicable law, the party initiating the arbitration will be responsible for paying the applicable filing fee. Each party will advance one-half of the fees and expenses of the arbitrator, the costs of the attendance of the arbitration reporter at the arbitration hearing and the costs of the arbitration facility. In any arbitration arising out of or relating to the Terms, the arbitrator will award to the prevailing party, if any, the costs and attorneys’ fees reasonably incurred by the prevailing party in connection with those aspects of its claims or defenses on which it prevails, and any opposing awards of costs and legal fees awards will be offset. </div>
                                
                        <div>            9.8. The parties will keep confidential the existence of the arbitration, the arbitration proceeding, the hearing and the arbitrator’s decision, except (a) as necessary to prepare for and conduct the arbitration hearing on the merits; (b) in connection with a court application for a preliminary remedy, or confirmation of an arbitrator’s decision or its enforcement; (c) Remex may disclose the arbitrator’s decision in confidential settlement negotiations; (d) each party may disclose as necessary to professional advisors that are subject to a strict duty of confidentiality; and (e) as applicable law otherwise requires. The parties, witnesses and arbitrator will treat as confidential and will not disclose to any third person (other than witnesses or experts) any documentary or other evidence produced in any arbitration, except as applicable law so requires or if the evidence was obtained from the public domain or was otherwise obtained independently from the arbitration. </div>
                                
                        <div>            9.9. In the case of a conflict between the provisions of this Section 9 and the rules of the ICDR, the provisions of this Section 9 shall prevail. </div>
                                
                        <div>            9.10. To the extent permitted by applicable law, any dispute arising out of or relating to the Terms, whether in arbitration or in court, shall be conducted only on an individual basis and not in a class, consolidated or representative action. Notwithstanding any other provision of the Terms or the rules of the ICDR, disputes regarding the interpretation, applicability or enforceability of this class waiver may be resolved only by a court and not by an arbitrator. If this waiver of class or consolidated actions is deemed invalid or unenforceable, neither party is entitled to arbitration. </div>
                                
                        <div>            9.11. If for any reason a claim or dispute proceeds in court rather than through arbitration, each party knowingly and irrevocably waives any right to trial by jury in any action, proceeding or counterclaim arising out of or relating to the Terms. </div>
                </div>
                </li>
                <li>
                <span className='font-bold'>10. Third Party Websites and Links.</span>
                <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>            10.1. Remex may allow access to third party information, products, services, and other materials (collectively “Third Party Materials”), including via links. The content of other websites, services, goods, advertisements, or other Third Party Materials that may be linked to or from the Services is not maintained, endorsed or controlled by us. We are therefore not responsible for the availability, content, validity, timeliness, completeness, reliability, integrity, quality, legality, usefulness, safety or accuracy of Third Party Materials, or any intellectual property rights therein, that may be linked to or from the Services. In addition, the availability of any Third Party Materials through the Services does not imply Remex’s endorsement of, or our affiliation with, any provider of such Third Party Materials, nor does such availability create any legal relationship between you and any such provider. Such third parties may have a privacy policy and/or terms of use that are different from Remex’s and may provide less security than Remex. Notwithstanding anything to the contrary herein, Remex is not responsible or liable for any such differences or discrepancies within the Third Party Materials. We do not: (a) make any warranty, express or implied, with respect to the use of the links provided on, or to, the Services; (b) verify or guarantee the accuracy, completeness, usefulness, or adequacy of any other websites, services, goods or other Third Party Materials that may be linked to or from the Services; or (c) make any endorsement, express or implied, of any other websites, services, goods or other Third Party Materials that may be linked to or from Services. You agree to access these other websites, services, goods, advertisements or other Third Party Materials at your own risk. For the avoidance of doubt, this paragraph covers websites linked to or from the Services. Any statements, opinions, or other information made available by third parties, including users, are solely those of the respective author(s) or distributor(s). </div>

                    <div>            10.2. WE DISCLAIM ANY AND ALL LIABILITY, INCLUDING ANY EXPRESS OR IMPLIED WARRANTIES, WHETHER ORAL OR WRITTEN, FOR WEBSITES, SERVICES, GOODS, INFORMATION, ADVERTISEMENTS OR OTHER THIRD PARTY MATERIALS THAT MAY BE LINKED TO OR FROM, OR PROVIDED THROUGH, THE SERVICES. YOU ACKNOWLEDGE THAT NO REPRESENTATION HAS BEEN MADE BY US AS TO THE FITNESS OF THE WEBSITES, SERVICES, GOODS, ADVERTISEMENTS OR OTHER THIRD PARTY MATERIALS THAT MAY BE LINKED TO OR FROM THE SERVICES. YOUR USE OF THIRD PARTY MATERIALS IS AT YOUR SOLE RISK AND IS SUBJECT TO ANY ADDITIONAL TERMS, CONDITIONS AND POLICIES APPLICABLE TO SUCH THIRD PARTY MATERIALS (SUCH AS TERMS OF USE OR PRIVACY POLICY OF THE PROVIDERS OF SUCH THIRD PARTY MATERIALS). </div>

                    <div>            10.3. You may link to the Services provided that you do so in a way that indicates that the link is direct to the Services and is fair and not misleading. You may not integrate or make use of all or part of the Services in ways that would confuse or mislead visitors as to the nature and origin of the Services’ content. </div>
                </div>
                </li>
                <li>
                <span className='font-bold'>11. General Provisions. </span>
                <div className='flex flex-col gap-[2rem] pl-[2%]'>
                    <div>            11.1. Electronic Communications. By accessing or using the Services, you consent to receive electronic communications. </div>

                    <div>            11.2. Notices. Remex may provide you with notice and other communications via electronic communications as permitted by Section 11.1. You may provide us with notice by sending an email address to info@Remexfi.com. All notices will be deemed effective upon dispatch. </div>

                    <div>            11.3. Waivers. For a waiver to be deemed effective, a waiver must be in a writing signed by the waiving party. The failure of either party to enforce any provision of the Terms will not constitute a waiver of that party’s rights to subsequently enforce the provision. </div>

                    <div>            11.4. Cumulative Rights; Injunctions. The rights and remedies of the parties under the Terms are cumulative, and each party may exercise any of its rights and enforce any of its remedies under the Terms, along with all other rights and remedies available to it at law, in equity or otherwise. Any material breach by a party of the Terms could cause the non-breaching party irreparable harm for which the non-breaching party has no adequate remedies at law. Accordingly, the non-breaching party is entitled to seek specific performance or injunctive relief for any such breach. </div>

                    <div>            11.5. Severability. If any provision of the Terms is declared to be invalid, illegal or unenforceable by a court of competent jurisdiction, then the validity, legality and enforceability of the remaining provisions contained herein shall not be affected thereby and the remainder of the provisions of the Terms shall remain valid, legal and enforceable to the fullest extent permitted by law. </div>

                    <div>            11.6. Accessibility. We are committed to helping those with disabilities access the Services. We strive to provide an excellent online experience for our users – including those with sight, hearing, and other disabilities. If you have difficulty using or accessing any element of the Services or if you have any feedback regarding accessibility of the Services, please feel free to contact us at info@Remexfi.com. </div>

                    <div>            11.7. Force Majeure. Remex shall have no liability for any failure or delay resulting from any condition beyond our reasonable control, including but not limited to governmental action or acts of terrorism, earthquake, fire, flood, or other acts of God, labor conditions, power failures, equipment failures and Internet or blockchain network disturbances. </div>

                    <div>            11.8. Successors and Assigns. You may not transfer or assign the Terms or any rights or obligations hereunder, by operation of law or otherwise and any such attempted assignment shall be void. Remex reserves the right to freely transfer or assign the Terms and the rights and obligations hereunder to any third party at any time without your consent and prior notice to you. If you object to any such transfer or assignment, you may stop using the Services. </div>

                    <div>            11.9. Relationship of the Parties. Nothing contained in the Terms shall constitute you and Remex as members of any partnership, joint venture, association, syndicate, unincorporated business or similar assignment as a result of or by virtue of the relationship established by the Terms. </div>

                    <div>            11.10. Governing Law. The Terms shall be solely and exclusively governed, construed and enforced in accordance with the laws of Cayman Islands without giving effect to conflict of law rules or principles that would cause the application of the laws of any other jurisdiction. </div>

                    <div>           11.11. Entire Agreement. The Terms constitute the entire agreement and understanding between you and Remex, and supersedes all previous communications, representations or agreements, whether written or oral, with respect to the subject matter hereof. </div>

                    <div>            11.12. No Third-Party Beneficiaries. The Terms are not intended and shall not be construed to create any rights or remedies in any parties other than you and Remex and other Remex affiliates, which each shall be a third-party beneficiary of the Terms, and no other person shall assert any rights as a third-party beneficiary hereunder. </div>
                </div>  
                    
                </li>
                </ul>
                </div>
            </div>
        </div>
    )
}
export default page;